## Hopfield

$$ dw=x.x^T -I \space \space \\ where \space \space I =\space identity \space matrix.$$  
$$w=w+dw$$

<b>Energy</b>
$$E=\frac{−1}{2} \sum_{j=1}^n  \sum_{i=1}^n w_{ij}x_i x_j$$

In terms of linear algebra, simpler version is 
$$E = -\frac{1}{2} x^T.W.x$$

In [1]:
import numpy as np  
import matplotlib.pyplot as plt
import random

In [2]:
#Neurons=9
N=9

In [3]:
x1=np.array([1,1,1, 0,0,0, 0,0,0])
x2=np.array([0,0,0, 0,0,0, 1,1,1])
x3=np.array([0,0,0, 1,1,1, 0,0,0])

In [4]:
w=np.zeros((N,N))
print(w)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


<b>First Task : Train x1</b></b>
Train x1 and update w and calculate energy.<br>
<b>updated w</b> should look like the following. <br>
       [ 0.,  1.,  1., -1., -1., -1., -1., -1., -1.],<br>
       [ 1.,  0.,  1., -1., -1., -1., -1., -1., -1.],<br>
       [ 1.,  1.,  0., -1., -1., -1., -1., -1., -1.],<br>
       [-1., -1., -1.,  0.,  1.,  1.,  1.,  1.,  1.],<br>
       [-1., -1., -1.,  1.,  0.,  1.,  1.,  1.,  1.],<br>
       [-1., -1., -1.,  1.,  1.,  0.,  1.,  1.,  1.],<br>
       [-1., -1., -1.,  1.,  1.,  1.,  0.,  1.,  1.],<br>
       [-1., -1., -1.,  1.,  1.,  1.,  1.,  0.,  1.],<br>
       [-1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  0.]]<br>
       
energy should be=-36

In [5]:
x1[x1==0]=-1

x2[x2==0]=-1

x3[x3==0]=-1

In [6]:

def cal_w(w,x):
    X=np.zeros((N,N))
    for i in range(len(x)):
        for j in range(len(x)):
            X[i][j]=x[i]*x[j]

    Identity=np.identity(N)
    X=np.subtract(X,Identity)
    return X

In [7]:
dw=cal_w(w,x1)
w=np.add(dw,w)
print(dw)

[[ 0.  1.  1. -1. -1. -1. -1. -1. -1.]
 [ 1.  0.  1. -1. -1. -1. -1. -1. -1.]
 [ 1.  1.  0. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1.  0.  1.  1.  1.  1.  1.]
 [-1. -1. -1.  1.  0.  1.  1.  1.  1.]
 [-1. -1. -1.  1.  1.  0.  1.  1.  1.]
 [-1. -1. -1.  1.  1.  1.  0.  1.  1.]
 [-1. -1. -1.  1.  1.  1.  1.  0.  1.]
 [-1. -1. -1.  1.  1.  1.  1.  1.  0.]]


In [8]:
E1 = np.dot(dw,x1.T)
E2 = np.dot(x1,E1)
Energy = -0.5*E2
print('Energy: ',Energy)

Energy:  -36.0


<b>Second Task : Train x2</b>
Train x2 and update w and calculate energy.<br>

In [9]:

dw=cal_w(w,x2)
w=np.add(dw,w)
print(dw)

[[ 0.  1.  1.  1.  1.  1. -1. -1. -1.]
 [ 1.  0.  1.  1.  1.  1. -1. -1. -1.]
 [ 1.  1.  0.  1.  1.  1. -1. -1. -1.]
 [ 1.  1.  1.  0.  1.  1. -1. -1. -1.]
 [ 1.  1.  1.  1.  0.  1. -1. -1. -1.]
 [ 1.  1.  1.  1.  1.  0. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1.  0.  1.  1.]
 [-1. -1. -1. -1. -1. -1.  1.  0.  1.]
 [-1. -1. -1. -1. -1. -1.  1.  1.  0.]]


In [10]:
E1 = np.dot(dw,x2.T)
E2 = np.dot(x2,E1)
Energy = -0.5*E2
print('Energy: ',Energy)

Energy:  -36.0


<b>Third Task : Train x3</b>
Train x3 and update w and calculate energy.<br>

In [11]:
dw=cal_w(w,x3)
w=np.add(dw,w)
print(dw)

[[ 0.  1.  1. -1. -1. -1.  1.  1.  1.]
 [ 1.  0.  1. -1. -1. -1.  1.  1.  1.]
 [ 1.  1.  0. -1. -1. -1.  1.  1.  1.]
 [-1. -1. -1.  0.  1.  1. -1. -1. -1.]
 [-1. -1. -1.  1.  0.  1. -1. -1. -1.]
 [-1. -1. -1.  1.  1.  0. -1. -1. -1.]
 [ 1.  1.  1. -1. -1. -1.  0.  1.  1.]
 [ 1.  1.  1. -1. -1. -1.  1.  0.  1.]
 [ 1.  1.  1. -1. -1. -1.  1.  1.  0.]]


In [12]:
E1 = np.dot(dw,x3.T)
E2 = np.dot(x3,E1)
Energy = -0.5*E2
print('Energy: ',Energy)

Energy:  -36.0


<b>Fourth Task : Asynchronous recovery</b> <br>
tx=np.array([0,0,0, 1,0,0, 0,0,0])  <br>

1. choose i randomly
2. update ith element of partial pattern tx 
3. Repeat step 2 for some time.

$$x_i=sign(w_i.x)$$

It should converge to a known pattern <br>[0, 0, 0, 1, 1, 1, 0, 0, 0]

In [13]:
def sign(val):
    if(val<0):
        return -1
    else:
        return 1

In [14]:
tx=np.array([0,0,0, 1,0,0, 0,0,0])

for i in range(100000):
    rnd=random.randint(0, 8)
    tx[rnd]=sign(np.dot(w[rnd],tx))

for i in range(len(tx)):
    if(tx[i]==-1):
        tx[i]=0
print(tx)

[1 1 1 1 1 1 0 0 0]
